### ISSUE TITLE
Update some engine-specific code

### ISSUE THREAD

**Issue by Danesprite** [dictation-toolbox/Caster#554]
Some of Caster's code for WSR and natlink is no longer necessary with recent changes to dragonfly. Changing a few things should make it easier to test with the "text" engine (#490) and use Caster with other engines.

- [x] Update *_caster.py* to use `engine.recognize_forever()` instead of the pump waiting messages loop if WSR is being used. The `recognize_forever()` engine method pumps waiting messages, calls timer functions set via `create_timer()` and updates grammar state on window changes (to fix an annoying bug).
- [ ] Use the normal `RecognitionHistory` class from dragonfly instead of the class in Caster's *wsrdf.py* file.
- [x] Use the `engine.create_timer()` method for all engines instead of dragonfly's `_Timer` class for natlink and the `TimerForWSR` class for WSR.

@LexiconCode Let me know what you think. It might take me a while to get to these and there may be other problems. Feel free to edit the post.

**Comment by LexiconCode** [comment]
Sounds good, thank you for opening an issue. With my clinical rotation I just don't have the time right now.

**Comment by Danesprite** [comment]
No problem. That's okay, I know you're very busy. I can probably submit a PR to fix the first two soon.

**Comment by LexiconCode** [comment]
Update `_caster.py` to use `engine.recognize_forever()` completed by https://github.com/dictation-toolbox/Caster/commit/0c8dddfed00f857d4159c41134ff026ab9fe8830

**Comment by Danesprite** [comment]
Thanks. The loop isn't necessary for that method. I'm about to fix the only remaining issue in a new PR, so I'll just remove the while loop in there.

**Comment by Danesprite** [comment]
The `_wait_for_wsr_activation()` function only really applies to `sapi5shared`, not `sapi5inproc`. Should it be removed?

**Comment by LexiconCode** [comment]
I would say remove it.
