### ISSUE TITLE
Utilize github release model and remove development branch.

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#617]
Here are some of the positives to the change.

- Documentations are versioned according to release with RTD. It can be
done with branches but it's cumbersome.
- No more concerns about recommending development versus master branch.
- No more cumbersome merges from development to master.
- The landing page (Master) will reflect the state of current development and githubs activity for the project.
- No more accidental commits to master the are meant for developmeant.
- Overall the industry seems to be turning away from using development branches
- The transition End-users from using caster to developing caster would be seamless.
- Simplifies install instructions

**Comment by LexiconCode** [comment]
Related add changelog and auto generate log with Travis.
https://github.com/dictation-toolbox/Caster/pull/443

**Comment by Danesprite** [comment]
This is a great idea. Doing this in dragonfly has simplified things so much for me.

**Comment by LexiconCode** [comment]
Preparing for the worse backing up Caster repo.
backup
```
git bundle create backup.bundle --all
```
restore
```
git clone backup.bundle -b <branch> Caster
```

**Comment by LexiconCode** [comment]
Transition to master branch complete with development branch deleted. Transferred open pull requests to master branch.

- [x] Synchronized master to develop
- [x] Transferred open pull requests to master branch.
- [ ] Check readme for broken links (most go to RTD versus .md)
- [ ] Update [Installation.md](https://github.com/dictation-toolbox/Caster/blob/master/castervoice/doc/Installation.md) 
- [ ] Update [Contributing.md](https://github.com/dictation-toolbox/Caster/blob/master/castervoice/doc/Contributing.md) 
- [ ] check config's and verify RTD/Travis function is expected

**Comment by LexiconCode** [comment]
Waiting on https://github.com/dictation-toolbox/Caster/pull/618 to simplify install process for classic install.
