### ISSUE TITLE
Overhaul _caster.py  

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#638]
Some thoughts to overhaulr `_caster.py `each of these checkboxes will be a separate pull request/issue.

- [x] Move Dependency checks and and install type out of _caster.py to dependencies.py https://github.com/dictation-toolbox/Caster/pull/610  

- [x] Re-factored _caster.py grammars to caster.py in apps. #639

- [x] Remove engine loading (WSR) mechanisms within _caster.py 
  This change will allow Caster to utilize [_any module loader_](https://github.com/dictation-toolbox/dragonfly/tree/master/dragonfly/examples) supported by dragonfly.

- [x]  How to choose between end-user WSR and DNS on first time caster.py startup? Than include WSR module loader file with _caster.py

  - Most likely is a separate issue to discuss how to install supported module loader dependencies

**Comment by LexiconCode** [comment]
In short Caster has leveraged this default state instead of explicitly calling `sapi5inproc`. This will change in the future as we figure out how to handle other engines as well in a unified system. 

- Integrating grammars from module loaders as apps calling engines explicitly  `get_engine("sapi5inproc")`
-  Leveraging module loader files from dragonfly. 
-  Utilize [Add dragonfly command for loading and recognising from command modules](https://github.com/dictation-toolbox/dragonfly/issues/98).

The first option is interesting as it gives us direct control over the grammars especially running filters on them as well. There is a 3rd option might change based on how https://github.com/dictation-toolbox/dragonfly/issues/98 is implemented.  There's the possibility of a config module could be used for engine configuration and setting up other functionality like the wake/sleep modes added by daanzu's module loaders for Kaldi and WSR. Although I'm not sure if casters filter rules can run on the config.

 There's the possibility of a config module could be used for engine configuration and setting up other functionality like the wake/sleep modes added by daanzu's module loaders for Kaldi and WSR. Although I'm not sure if casters filter rules can run on the config.
