### ISSUE TITLE
Command Issue Tracker

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#781]
## Command Issue Tracker
The goal of this thread is to keep track of existing commands that may need to be re-implemented or reevaluated in some way. Users should reply to this thread with the template. Once the issue is reviewed it will be added to the main post in the users post will be marked as outdated.

### List Commands that need to be reimplemented or re-evaluated:

- [ ]  Command: **"change monitor"**

	Intended action - Changes focus from one monitor to another
	Current action - opens up sidebar to change monitors in Windows 10
	Notes - Needs cross-platform implementation
	Related command/feature: SikuliX to search alternative monitors for images
	file/grammar name - hardware_rule.py

- [ ]  Command: **browse** 

	Intended action - Brings up the GUI to browse folder locations via directory path
	Current action - Browse not recognized as command/Does not launch GUI
	Notes - Really old command.
	Related command/feature - GUI
	location - hmc_directory_rule.py

### Template
```
- [ ]  Command: ** ** # The Exact spec

	Intended action -
	Current action - 
	Notes - 
	Related command/feature -
	file/grammar name - 
```

**Comment by kendonB** [comment]
- [ ]  Command: **switch window**

	Intended action - The switch window (alt tab) display comes up and stays up. 
	Current action - Nothing (it is a Dragon command).
	Notes - The only solution on Ubuntu I believe is to press alt tab and hold alt. This also requires a "release alt" command to be implemented. See #850. On Windows it will be Ctrl-Alt-Tab.
	Related command/feature - None
	file/grammar name - should be put into `window_mgmt_rule.py`
